//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Racunovodstvo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod()
        {
            this.StavkaPopisas = new HashSet<StavkaPopisa>();
            this.Zalihes = new HashSet<Zalihe>();
            this.Karakteristikas = new HashSet<Karakteristika>();
        }
    
        public int id { get; set; }
        public string naziv { get; set; }
        public double minimumkolicine { get; set; }
        public int jedinicamere_id { get; set; }
        public string sifra { get; set; }
        public int proizvodjac_id { get; set; }
    
        public virtual jedinicamere jedinicamere { get; set; }
        public virtual Proizvodjac Proizvodjac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaPopisa> StavkaPopisas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zalihe> Zalihes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karakteristika> Karakteristikas { get; set; }
    }
}
