//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Racunovodstvo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaKompenzacije
    {
        public int stavkafakture_faktura_id { get; set; }
        public int stavkafakture_rednibroj { get; set; }
        public int kompenzacija_id { get; set; }
        public int kolicina { get; set; }
        public int rednibroj { get; set; }
    
        public virtual Kompenzacija Kompenzacija { get; set; }
        public virtual StavkaFakture StavkaFakture { get; set; }
    }
}
