//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktura()
        {
            this.Opomenas = new HashSet<Opomena>();
            this.Profakturas = new HashSet<Profaktura>();
            this.StavkaFaktures = new HashSet<StavkaFakture>();
            this.SkladisteniDokuments = new HashSet<SkladisteniDokument>();
            this.Faktura1 = new HashSet<Faktura>();
            this.Fakturas = new HashSet<Faktura>();
        }
    
        public Nullable<System.DateTime> datumfakturisanja { get; set; }
        public bool upripremi { get; set; }
        public int id { get; set; }
        public bool active { get; set; }
        public int zaposleni_id { get; set; }
        public Nullable<System.DateTime> datumprometadobara { get; set; }
        public bool redovna { get; set; }
        public bool ulazna { get; set; }
        public Nullable<double> placeno { get; set; }
        public Nullable<double> pdv { get; set; }
        public Nullable<bool> otpremljena { get; set; }
        public Nullable<System.DateTime> rokplacanja { get; set; }
        public Nullable<bool> avansnoplacanje { get; set; }
        public Nullable<double> avans { get; set; }
        public Nullable<int> profaktura_id { get; set; }
        public Nullable<bool> likvidirano { get; set; }
        public Nullable<int> poslovnipartner_mbr { get; set; }
        public Nullable<bool> stornoceo { get; set; }
        public string oznaka { get; set; }
    
        public virtual Zaposleni Zaposleni { get; set; }
        public virtual PoslovniPartner PoslovniPartner { get; set; }
        public virtual Profaktura Profaktura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opomena> Opomenas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profaktura> Profakturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaFakture> StavkaFaktures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkladisteniDokument> SkladisteniDokuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Faktura1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Fakturas { get; set; }
    }
}
