//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaPopisa
    {
        public int rednibroj { get; set; }
        public double kolicina { get; set; }
        public int proizvod_id { get; set; }
        public int popis_id { get; set; }
        public int skladiste_id { get; set; }
        public string raf { get; set; }
    
        public virtual Popi Popi { get; set; }
        public virtual Proizvod Proizvod { get; set; }
        public virtual Skladiste Skladiste { get; set; }
    }
}
