//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaSklDokumenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StavkaSklDokumenta()
        {
            this.StavkaFaktures = new HashSet<StavkaFakture>();
        }
    
        public bool storno { get; set; }
        public double kolicina { get; set; }
        public int rednibroj { get; set; }
        public int zalihe_proizvod_id { get; set; }
        public int zalihe_idskladista { get; set; }
        public int skladistenidokument_id { get; set; }
        public Nullable<int> stavkafakture_faktura_id { get; set; }
        public Nullable<int> stavkafakture_rednibroj { get; set; }
    
        public virtual SkladisteniDokument SkladisteniDokument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaFakture> StavkaFaktures { get; set; }
        public virtual StavkaFakture StavkaFakture { get; set; }
        public virtual Zalihe Zalihe { get; set; }
    }
}
