//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zalihe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zalihe()
        {
            this.StavkaFaktures = new HashSet<StavkaFakture>();
            this.StavkaProfaktures = new HashSet<StavkaProfakture>();
            this.StavkaSklDokumentas = new HashSet<StavkaSklDokumenta>();
        }
    
        public double kolicina { get; set; }
        public double minimumkolicine { get; set; }
        public int proizvod_id { get; set; }
        public int skladiste_id { get; set; }
        public string raf { get; set; }
        public double rezervisano { get; set; }
    
        public virtual Proizvod Proizvod { get; set; }
        public virtual Skladiste Skladiste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaFakture> StavkaFaktures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaProfakture> StavkaProfaktures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaSklDokumenta> StavkaSklDokumentas { get; set; }
    }
}
