//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladistenje.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaProfakture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StavkaProfakture()
        {
            this.StavkaFaktures = new HashSet<StavkaFakture>();
        }
    
        public double kolicina { get; set; }
        public double rabat { get; set; }
        public double cena { get; set; }
        public int rednibroj { get; set; }
        public int profaktura_id { get; set; }
        public int zalihe_proizvod_id { get; set; }
        public int zalihe_skladiste_id { get; set; }
        public Nullable<int> stavkafakture_faktura_id { get; set; }
        public Nullable<int> stavkafakture_rednibroj { get; set; }
    
        public virtual Profaktura Profaktura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaFakture> StavkaFaktures { get; set; }
        public virtual StavkaFakture StavkaFakture { get; set; }
        public virtual Zalihe Zalihe { get; set; }
    }
}
