//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladistenje.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposleni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zaposleni()
        {
            this.Fakturas = new HashSet<Faktura>();
            this.Kompenzacijas = new HashSet<Kompenzacija>();
            this.Korisniks = new HashSet<Korisnik>();
            this.Profakturas = new HashSet<Profaktura>();
            this.Zaposleni1 = new HashSet<Zaposleni>();
            this.ZaposleniSkladistas = new HashSet<ZaposleniSkladista>();
            this.Popis = new HashSet<Popi>();
            this.Ulogas = new HashSet<Uloga>();
        }
    
        public int id { get; set; }
        public string jmbg { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public double plata { get; set; }
        public double doprinosi { get; set; }
        public double bonus { get; set; }
        public string adresa { get; set; }
        public string email { get; set; }
        public string tekuciracun { get; set; }
        public string brojtelefona { get; set; }
        public Nullable<int> sef_id { get; set; }
        public int grad_id { get; set; }
        public bool active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Fakturas { get; set; }
        public virtual grad grad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kompenzacija> Kompenzacijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korisnik> Korisniks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profaktura> Profakturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaposleni> Zaposleni1 { get; set; }
        public virtual Zaposleni Zaposleni2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZaposleniSkladista> ZaposleniSkladistas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Popi> Popis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uloga> Ulogas { get; set; }
    }
}
